name: petclininc
on: 
  - workflow_dispatch
jobs: 
   Build: 
     runs-on: 'ubuntu-latest'
     steps: 
       - name: Build our application
         run: |
            git clone https://github.com/Nimisha-Chonattil/spring-petclinic.git
            ls
            cd spring-petclinic/
            ls
            pwd

  