name: Upload artifact
on: workflow_dispatch

jobs:
  artifact:
    name: Upload artifact to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      # - name: Set up JDK 17
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: 17
      #     distribution: 'zulu' 
      - name: Upload artifact
        uses: actions/upload-artifact@2
        with:
          name: petclinic's artifact
          path: target/*.jar
